name: Deploy Azure Storage Account

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check/Create Resource Group
        run: |
          if ! az group show --name bicep-rg --query -id -o tsv 2>/dev/null; then
            az group create --name bicep-rg --location eastus
            echo "Resource Group Created"
          else
            echo "Resource group already exists"
          fi

      - name:
        run: |
          SHORT_RUN_ID=$(echo "${{ github.run_id }}" | tail -c 4)
          az deployment group create \
            --resource-group bicep-rg \
            --template-file files/storage-account.bicep \
            --parameters \
                storageAccountName="stg${SHORT_RUN_ID}" \
                location='eastus' \
                storageAccountType='Standard_LRS'